#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TinnAwayAndroid.Resource", IsApplication=true)]

namespace TinnAwayAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int bAlarmClock = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int bAuthoredMusic = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int bFindYourFrequency = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int bRecordMusic = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int bSettings = 2131099656;
			
			// aapt resource value: 0x7f060001
			public const int bSoundGenerator = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int bSoundMixer = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int bSoundsOfNature = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int lvSongs = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int authored_music = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int FruityFallsSong = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int alarm_clock = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int authored_music = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int find_your_frequency = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int play = 2131034122;
			
			// aapt resource value: 0x7f050007
			public const int record_music = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int settings = 2131034121;
			
			// aapt resource value: 0x7f050002
			public const int sound_generator = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int sound_mixer = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int sounds_of_nature = 2131034116;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
